name: Shopping List Organizer
version: "1.0.1"
slug: shop
description: Voice-to-print shopping list processor
arch:
  - armv7
# Build from Dockerfile
startup: application
init: false
url: https://github.com/Homlet/shop
webui: http://[HOST]:[PORT:8080]
homeassistant_api: true
auth_api: true
ingress: true
ingress_port: 8080
ingress_title: Shopping List Organizer
panel_icon: mdi:clipboard-list
panel_title: Shopping List
panel_admin: false
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface
options:
  llm_model: "gpt-3.5-turbo"
  llm_api_key: ""
  todo_list_entity_id: "todo.shopping"
  default_store: "Grocery Store"
  receipt_width: 32
  log_level: "INFO"
  stores:
    - name: "Grocery Store"
      sections:
        - "Produce"
        - "Dairy"
        - "Meat"
        - "Pantry"
        - "Frozen"
        - "Household"
    - name: "Supermarket"
      sections:
        - "Fruits & Vegetables"
        - "Dairy & Eggs"
        - "Meat & Seafood" 
        - "Bakery"
        - "Canned Goods"
        - "Frozen Foods"
        - "Cleaning Supplies"
    - name: "Convenience Store"
      sections:
        - "Snacks"
        - "Beverages"
        - "Quick Meals"
        - "Essentials"
schema:
  llm_model: str
  llm_api_key: password
  todo_list_entity_id: str
  default_store: str
  receipt_width: int(32,48)
  log_level: list(DEBUG,INFO,WARNING,ERROR)
  stores:
    - name: str
      sections:
        - str