name: Shopping List Organiser
version: "1.2.1"
slug: shop
description: Voice-to-print shopping list processor
url: https://github.com/Homlet/shop
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: auto
init: false
webui: http://[HOST]:[PORT:8080]

homeassistant_api: true

ingress: true
ingress_port: 8080

panel_icon: mdi:invoice-list
panel_admin: false

ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface

schema:
  llm_model: str
  llm_api_key: password
  todo_list_entity_id: str
  default_store: str
  receipt_width: int(32,48)
  log_level: list(DEBUG|INFO|WARNING|ERROR)
  stores:
    - name: str
      sections:
        - str
options:
  llm_model: ""
  llm_api_key: ""
  todo_list_entity_id: "todo.shopping"
  default_store: "Newmarket Tesco"
  receipt_width: 38
  log_level: "INFO"
  stores:
    - name: Newmarket Tesco
      sections:
        - Vegetables
        - Bakery
        - Fruit
        - Flowers
        - Garden
        - Homeware
        - Baby
        - Toiletries
        - Pharmacy
        - Cleaning
        - Pet
        - Clothing
        - Drinks
        - Snacks & Confectionery
        - Store Cupboard
        - Meat & Fish
        - Ready-to-eat
        - Dairy
    - name: Ely Sainsbury's
      sections:
        - Homeware
        - Clothing
        - Garden
        - Fruit
        - Vegetables
        - Ready-to-eat
        - Meat & Fish
        - Dairy
        - Bakery
        - Store Cupboard
        - Snacks & Confectionery
        - Drinks
        - Pet
        - Cleaning
        - Baby
        - Toiletries
        - Pharmacy
        - Flowers
    - name: Soham Asda
      sections:
        - Flowers
        - Vegetables
        - Fruit
        - Meat & Fish
        - Ready-to-eat
        - Dairy
        - Store Cupboard
        - Bakery
        - Snacks & Confectionery
        - Garden
        - Homeware
        - Drinks
        - Pet
        - Toiletries
        - Baby
        - Pharmacy
        - Cleaning
